name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build-and-test:
    permissions:
      attestations: write
      contents: read
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      # - run: opam install . --deps-only --with-test
      - run: opam install base stdio ounit.2.2.7 dune -y

      - run: opam exec -- dune build
      # - run: opam exec -- dune runtest

  lint-opam:
    permissions:
      attestations: write
      contents: read
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      
      - run: opam install zanuda.1.0.0 -y

      - run: opam exec -- zanuda ./bin/*.ml ./test/*.ml 
